"""Initial migration

Revision ID: 2fa4dd0aa0a8
Revises: None
Create Date: 2015-03-16 15:47:51.669000

"""

# revision identifiers, used by Alembic.
revision = '2fa4dd0aa0a8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
